### ISSUE TITLE
Application Crashes Immediately On Screenshot

### ISSUE THREAD

**Issue by kryptonianson** [jeremyvizzini/ScreenToLayers#1]
For some reason, no matter what I do, the application crashes immediately when (the symptom it appears) trying to write the screenshot to disk. I have not been able to take a single screenshot yet.

**Comment by jeremyvizzini** [comment]
Thank you for feedback.
I didn't have any other message about crashes.
So I have a lot of questions ...

Can you tell me more about your setup ? 
  - Do you have a retina screen ? 
  - How many monitors do you have ?
  - Which OS are you using ?
Moreover, did you change the default output directory ?
To conclude, can you post the beginning of crash report ?

**Comment by kryptonianson** [comment]
Jeremy,

So, I found that it is conflicting with an application. I verified this as well on a totally separate machine. It is conflicting with:

    http://tracesof.net/uebersicht/

My suspicion is your app doesn’t know how to deal with the desktop “layers” for the widgets. Perhaps on your machine you can try a vanilla install of uebersicht without additional wigets and see if the same happens to you. Perhaps there is a specific widget it is choking on in my case. Let me know if I need to go through the trouble of narrowing that down if needed.

If I close the app everything works. At least I know what to do, but ironically it was that app I was wanting to do screenshots of. Not the end of the world, but anyhow, here is the other information (though I am not sure the system setup info is relevant).

My setup:

- macOS Sierra
- MacBook Pro Retina 13”
- One monitor
- I have tried multiple output locations including the default location (in case it was choking on the new Documents iCloud feature) with the same result.
- I uninstalled/reinstalled (using AppCleaner to remove the app to make sure “everything" was reasonably gone) with no change

And here is the relevant crash report information (and thanks for your response :) ):

Process:               ScreenToLayers [6687]
Path:                  /Applications/ScreenToLayers.app/Contents/MacOS/ScreenToLayers
Identifier:            com.jeremyvizzini.screentolayers.osx
Version:               1.0.4 (6)
OS Version:            Mac OS X 10.12 (16A320)

Crashed Thread:        4  Dispatch queue: com.apple.root.background-qos

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0:
--> 
    __TEXT                 0000000107e2e000-0000000107e3d000 [   60K] r-x/rwx SM=COW  /Applications/ScreenToLayers.app/Contents/MacOS/ScreenToLayers

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fffd70a441a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fffd70a3867 mach_msg + 55
2   com.apple.CoreFoundation      	0x00007fffc1f3e8d4 __CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation      	0x00007fffc1f3dd61 __CFRunLoopRun + 1361
4   com.apple.CoreFoundation      	0x00007fffc1f3d5b4 CFRunLoopRunSpecific + 420
5   com.apple.HIToolbox           	0x00007fffc14def6c RunCurrentEventLoopInMode + 240
6   com.apple.HIToolbox           	0x00007fffc14deda1 ReceiveNextEventCommon + 432
7   com.apple.HIToolbox           	0x00007fffc14debd6 _BlockUntilNextEventMatchingListInModeWithFilter + 71
8   com.apple.AppKit              	0x00007fffbfbd55f5 _DPSNextEvent + 1093
9   com.apple.AppKit              	0x00007fffc02e58eb -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1637
10  com.apple.AppKit              	0x00007fffbfbc9fbd -[NSApplication run] + 926
11  com.apple.AppKit              	0x00007fffbfb94a8a NSApplicationMain + 1237
12  libdyld.dylib                 	0x00007fffd6f7d255 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fffd7193214 start_wqthread + 0

Thread 2:
0   libsystem_kernel.dylib        	0x00007fffd70ac4e6 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffd7193632 _pthread_wqthread + 1023
2   libsystem_pthread.dylib       	0x00007fffd7193221 start_wqthread + 13

Thread 3:
0   libsystem_pthread.dylib       	0x00007fffd7193214 start_wqthread + 0

Thread 4 Crashed:: Dispatch queue: com.apple.root.background-qos
0   libsystem_platform.dylib      	0x00007fffd718cf3d _platform_memmove$VARIANT$Haswell + 157
1   com.apple.Foundation          	0x00007fffc392f1a7 -[NSConcreteMutableData appendBytes:length:] + 557
2   com.jeremyvizzini.screentolayers.osx	0x0000000107e31645 0x107e2e000 + 13893
3   com.jeremyvizzini.screentolayers.osx	0x0000000107e343c9 0x107e2e000 + 25545
4   com.jeremyvizzini.screentolayers.osx	0x0000000107e350c6 0x107e2e000 + 28870
5   com.jeremyvizzini.screentolayers.osx	0x0000000107e35784 0x107e2e000 + 30596
6   libdispatch.dylib             	0x00007fffd6f4ff5f _dispatch_call_block_and_release + 12
7   libdispatch.dylib             	0x00007fffd6f47128 _dispatch_client_callout + 8
8   libdispatch.dylib             	0x00007fffd6f49099 _dispatch_root_queue_drain + 917
9   libdispatch.dylib             	0x00007fffd6f48cb7 _dispatch_worker_thread3 + 99
10  libsystem_pthread.dylib       	0x00007fffd7193746 _pthread_wqthread + 1299
11  libsystem_pthread.dylib       	0x00007fffd7193221 start_wqthread + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fffd70a446e semaphore_timedwait_trap + 10
1   libdispatch.dylib             	0x00007fffd6f502c2 _dispatch_semaphore_wait_slow + 103
2   libdispatch.dylib             	0x00007fffd6f4aa94 _dispatch_worker_thread + 275
3   libsystem_pthread.dylib       	0x00007fffd7193abb _pthread_body + 180
4   libsystem_pthread.dylib       	0x00007fffd7193a07 _pthread_start + 286
5   libsystem_pthread.dylib       	0x00007fffd7193231 thread_start + 13

Thread 6:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fffd70a441a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fffd70a3867 mach_msg + 55
2   com.apple.CoreFoundation      	0x00007fffc1f3e8d4 __CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation      	0x00007fffc1f3dd61 __CFRunLoopRun + 1361
4   com.apple.CoreFoundation      	0x00007fffc1f3d5b4 CFRunLoopRunSpecific + 420
5   com.apple.AppKit              	0x00007fffbfd21e9e _NSEventThread + 205
6   libsystem_pthread.dylib       	0x00007fffd7193abb _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffd7193a07 _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffd7193231 thread_start + 13

Thread 4 crashed with X86 Thread State (64-bit):
  rax: 0x00006080001ffee9  rbx: 0x0000000000000000  rcx: 0x00006080001ffe00  rdx: 0x0000000000000007
  rdi: 0x00006080001ffee9  rsi: 0x0000000000000000  rbp: 0x000070000e3c1a30  rsp: 0x000070000e3c1a30
   r8: 0x0000000000000020   r9: 0x0000000000000000  r10: 0x00007fffdcb37c28  r11: 0x00006080001ffee9
  r12: 0x0000000000000000  r13: 0x000000000000000f  r14: 0x000060800024da10  r15: 0x00006080001ffee9
  rip: 0x00007fffd718cf3d  rfl: 0x0000000000010202  cr2: 0x0000000000000000
  
Logical CPU:     3
Error Code:      0x00000004
Trap Number:     14

**Comment by jeremyvizzini** [comment]
Thanks you so much for the very helpful response.

I downloaded Übersicht and fix the problem.
A problem due to the Ü in the name of the application.

If you try to compile the actual version (available on GitHub), it shoulds work fine.
I will send to apple the new version.

**Comment by kryptonianson** [comment]
Ahhh it doesn’t handle the umlaut diacritic. Makes sense. Thanks!

John

**Comment by jeremyvizzini** [comment]
The updated version is released.

**Comment by kryptonianson** [comment]
Thanks. Works great!
