### ISSUE TITLE
Mention single display only

### ISSUE THREAD

**Issue by Gatada** [jeremyvizzini/ScreenToLayers#2]
Hey,

Nice work! Just downloaded from the MacAppStore. Tweeted about it. Works great - as long as the user only has a single-display setup. With two screens at least, the output in my tests so far gets cropped.

I'm not sure how to fix it, but I'll take a look at the code when my time allows.

Anyway, fixed or not, you should just add that limitation to the readme/product description.

Very cool this.

**Comment by jeremyvizzini** [comment]
Hi, 

Thanks for the compliments and the tweet.
I am working on multi-screens support and that's why I didn't mention something in the description. I thought the compatibility will be easy to add but it's not. Just wait few days and it will be fixed.

**Comment by Gatada** [comment]
Nice! Do you need any UI assets let me know.

**Comment by jeremyvizzini** [comment]
Hi Gatada,

It takes me a long time but ScreenToLayers supports multi-screens now.
You can test the version available on master branch of this repository.
I will test the application on others configurations and then send it to Apple.

**Comment by Gatada** [comment]
Sorry for late reply; already downloaded from the AppStore and it works great.

Good work!

You are not in Twitter?

**Comment by jeremyvizzini** [comment]
I just created an account today. Thank you for tweeting about ScreenToLayers !! 👍
